- name: Setup Flask Dashboard on EC2
  hosts: web
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - python3
          - nginx
        state: present

    - name: Install pip3 using yum
      command: yum install -y python3-pip

    - name: Install Python packages
      pip:
        name:
          - flask
          - gunicorn
        executable: /usr/bin/pip3

    - name: Copy app files
      copy:
        src: "{{ item }}"
        dest: /home/ec2-user/
      with_items:
        - ../app.py
        - ../requirements.txt
        - ../gunicorn_config.py

    - name: Create Gunicorn systemd service
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn daemon for Flask App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user
          ExecStart=/usr/local/bin/gunicorn -c gunicorn_config.py app:app

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: started

    - name: Configure Nginx
      copy:
        dest: /etc/nginx/conf.d/flaskapp.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
